/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../pages/__root'
import { Route as adminLayoutRouteImport } from './../pages/(admin)/layout'
import { Route as IndexRouteImport } from './../pages/index'
import { Route as errors500RouteImport } from './../pages/(errors)/500'
import { Route as errors404RouteImport } from './../pages/(errors)/404'
import { Route as errors403RouteImport } from './../pages/(errors)/403'
import { Route as authLoginLayoutRouteImport } from './../pages/(auth)/login/layout'
import { Route as authLoginIndexRouteImport } from './../pages/(auth)/login/index'
import { Route as adminListIndexRouteImport } from './../pages/(admin)/list/index'
import { Route as adminHomeIndexRouteImport } from './../pages/(admin)/home/index'
import { Route as adminUsersUserIdRouteImport } from './../pages/(admin)/users/$userId'
import { Route as adminListUseProTableIndexRouteImport } from './../pages/(admin)/list/useProTable/index'
import { Route as adminListUseProTableDetailIndexRouteImport } from './../pages/(admin)/list/useProTable/detail/index'

const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginLayoutRoute = authLoginLayoutRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authLoginLayoutRoute,
} as any)
const adminListIndexRoute = adminListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminHomeIndexRoute = adminHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminUsersUserIdRoute = adminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => adminLayoutRoute,
} as any)
const adminListUseProTableIndexRoute =
  adminListUseProTableIndexRouteImport.update({
    id: '/list/useProTable/',
    path: '/list/useProTable/',
    getParentRoute: () => adminLayoutRoute,
  } as any)
const adminListUseProTableDetailIndexRoute =
  adminListUseProTableDetailIndexRouteImport.update({
    id: '/list/useProTable/detail/',
    path: '/list/useProTable/detail/',
    getParentRoute: () => adminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginLayoutRouteWithChildren
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/users/$userId': typeof adminUsersUserIdRoute
  '/home/': typeof adminHomeIndexRoute
  '/list/': typeof adminListIndexRoute
  '/login/': typeof authLoginIndexRoute
  '/list/useProTable/': typeof adminListUseProTableIndexRoute
  '/list/useProTable/detail/': typeof adminListUseProTableDetailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/users/$userId': typeof adminUsersUserIdRoute
  '/home': typeof adminHomeIndexRoute
  '/list': typeof adminListIndexRoute
  '/login': typeof authLoginIndexRoute
  '/list/useProTable': typeof adminListUseProTableIndexRoute
  '/list/useProTable/detail': typeof adminListUseProTableDetailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/(auth)/login': typeof authLoginLayoutRouteWithChildren
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(admin)/users/$userId': typeof adminUsersUserIdRoute
  '/(admin)/home/': typeof adminHomeIndexRoute
  '/(admin)/list/': typeof adminListIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(admin)/list/useProTable/': typeof adminListUseProTableIndexRoute
  '/(admin)/list/useProTable/detail/': typeof adminListUseProTableDetailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/403'
    | '/404'
    | '/500'
    | '/users/$userId'
    | '/home/'
    | '/list/'
    | '/login/'
    | '/list/useProTable/'
    | '/list/useProTable/detail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/users/$userId'
    | '/home'
    | '/list'
    | '/login'
    | '/list/useProTable'
    | '/list/useProTable/detail'
  id:
    | '__root__'
    | '/'
    | '/(admin)'
    | '/(auth)/login'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(admin)/users/$userId'
    | '/(admin)/home/'
    | '/(admin)/list/'
    | '/(auth)/login/'
    | '/(admin)/list/useProTable/'
    | '/(admin)/list/useProTable/detail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  authLoginLayoutRoute: typeof authLoginLayoutRouteWithChildren
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof authLoginLayoutRoute
    }
    '/(admin)/list/': {
      id: '/(admin)/list/'
      path: '/list'
      fullPath: '/list/'
      preLoaderRoute: typeof adminListIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/home/': {
      id: '/(admin)/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof adminHomeIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/users/$userId': {
      id: '/(admin)/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof adminUsersUserIdRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/list/useProTable/': {
      id: '/(admin)/list/useProTable/'
      path: '/list/useProTable'
      fullPath: '/list/useProTable/'
      preLoaderRoute: typeof adminListUseProTableIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
    '/(admin)/list/useProTable/detail/': {
      id: '/(admin)/list/useProTable/detail/'
      path: '/list/useProTable/detail'
      fullPath: '/list/useProTable/detail/'
      preLoaderRoute: typeof adminListUseProTableDetailIndexRouteImport
      parentRoute: typeof adminLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  adminUsersUserIdRoute: typeof adminUsersUserIdRoute
  adminHomeIndexRoute: typeof adminHomeIndexRoute
  adminListIndexRoute: typeof adminListIndexRoute
  adminListUseProTableIndexRoute: typeof adminListUseProTableIndexRoute
  adminListUseProTableDetailIndexRoute: typeof adminListUseProTableDetailIndexRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  adminUsersUserIdRoute: adminUsersUserIdRoute,
  adminHomeIndexRoute: adminHomeIndexRoute,
  adminListIndexRoute: adminListIndexRoute,
  adminListUseProTableIndexRoute: adminListUseProTableIndexRoute,
  adminListUseProTableDetailIndexRoute: adminListUseProTableDetailIndexRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

interface authLoginLayoutRouteChildren {
  authLoginIndexRoute: typeof authLoginIndexRoute
}

const authLoginLayoutRouteChildren: authLoginLayoutRouteChildren = {
  authLoginIndexRoute: authLoginIndexRoute,
}

const authLoginLayoutRouteWithChildren = authLoginLayoutRoute._addFileChildren(
  authLoginLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  adminLayoutRoute: adminLayoutRouteWithChildren,
  authLoginLayoutRoute: authLoginLayoutRouteWithChildren,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
