/**
 * ri 图标子集抽取：ri-manifest.json（人工清单）→ ri-local.json（IconifyJSON 生成物）
 * 用法：pnpm icons:build（改清单后必跑；生成物提交 git，运行时零依赖本脚本）
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { getIcons } from '@iconify/utils';

const manifestURL = new URL('../src/assets/icons/ri-manifest.json', import.meta.url);
const outputURL = new URL('../src/assets/icons/ri-local.json', import.meta.url);
const riFullURL = new URL('../node_modules/@iconify-json/ri/icons.json', import.meta.url);

const manifest = JSON.parse(readFileSync(manifestURL, 'utf8'));
const riFull = JSON.parse(readFileSync(riFullURL, 'utf8'));

const bad = manifest.filter(item => !item.name?.startsWith('ri:') || !item.label);
if (bad.length) {
  console.error(`[icons] 清单项缺 ri: 前缀或 label：${bad.map(i => i.name).join(', ')}`);
  process.exit(1);
}

const names = manifest.map(item => item.name.slice(3));
const dup = [...new Set(names.filter((n, i) => names.indexOf(n) !== i))];
if (dup.length) {
  console.error(`[icons] 清单重复：${dup.join(', ')}`);
  process.exit(1);
}

const subset = getIcons(riFull, names, true);
if (subset.not_found?.length) {
  console.error(`[icons] ri 集合中不存在：${subset.not_found.map(n => `ri:${n}`).join(', ')}`);
  process.exit(1);
}
delete subset.not_found;

writeFileSync(outputURL, JSON.stringify({ '//': 'GENERATED by pnpm icons:build - DO NOT EDIT', ...subset }, null, 2) + '\n');
console.log(`[icons] 生成 ri-local.json：${names.length} 个图标`);
